apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet
metadata:
  name: gameserver
  namespace: test
spec:
  replicas: 10
  updateStrategy:
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
  gameServerTemplate:
    spec:
      containers:
        - image: imroc/openkruise-dummy-gameserver:latest
          imagePullPolicy: Always
          name: gameserver
          env:
            - name: ROOM_TOTAL
              value: "1"
            - name: ALLOCATED_ROOM_RATIO
              value: "70"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
