apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet
metadata:
  name: gameserver
spec:
  replicas: 10
  updateStrategy:
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
  serviceQualities:
    - name: idle
      containerName: gameserver
      permanent: false
      exec:
        command: ["bash", "/check-idle.sh"]
      serviceQualityAction:
        - state: true # 不存在玩家，标记该游戏服运维状态为WaitToBeDeleted
          opsState: WaitToBeDeleted
        - state: false # 存在玩家，标记该游戏服运维状态为None
          opsState: None
  gameServerTemplate:
    spec:
      containers:
        - image: imroc/openkruise-dummy-gameserver:latest
          imagePullPolicy: Always
          name: gameserver
          env:
            - name: ROOM_TOTAL
              value: "1"
            - name: ALLOCATED_ROOM_RATIO
              value: "50"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
