apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: gameserver
spec:
  scaleTargetRef:
    apiVersion: game.kruise.io/v1alpha1
    kind: GameServerSet
    name: gameserver
  pollingInterval: 5
  minReplicaCount: 1
  maxReplicaCount: 100
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 120
          policies:
            - type: Percent
              value: 10
              periodSeconds: 120
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.monitoring:9090
        query: |
          count(game_room_allocated_total{namespace="test", service="gameserver"}) * sum(game_room_allocated_total{namespace="test", service="gameserver"}) / sum(game_room_total{namespace="test", service="gameserver"})
        threshold: "0.7" # 扩缩容阈值：70% 的房间占用率
