apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gameserver
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      game.kruise.io/owner-gss: gameserver
  endpoints:
    - port: metrics
