apiVersion: v1
kind: Service
metadata:
  name: gameserver
  labels:
    app: gameserver
spec:
  type: ClusterIP
  ports:
    - port: 8099
      name: metrics
      protocol: TCP
      targetPort: 8099
    - port: 8080
      name: api
      protocol: TCP
      targetPort: 8080
  selector:
    app: gameserver
