apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: game-room
spec:
  endpoints:
    - honorLabels: true
      port: "8099"
      interval: 5s
  namespaceSelector:
    matchNames:
      - test
  selector:
    matchLabels:
      game.kruise.io/owner-gss: gameserver
